### ISSUE TITLE
Web App Error

### ISSUE THREAD

**Issue by AndreSacra** [StepKie/MtgCsvHelper#17]
**Describe the bug**
When accessing the web app, it never fully loads, and an error occurs.

**To Reproduce**
1. Go to https://stepkie.github.io/MtgCsvHelper/
2. Wait for it to load.
3. "An unhandled error has occurred. Reload".

**Additional context**
When inspecting the console, an error shows up: "vt is undefined".

**Comment by StepKie** [comment]
Hi @AndreSacra,

thanks for reporting this issue. The root cause was a faulty .NET upgrade, which I have rolled back.
The updated version is deployed, please remember to clear your site data if you still encounter the issue.

I did not foresee this error, since the problem still compiled fine and unit test suite ran successfully.

Sorry for the incovenience and best regards.

**Comment by AndreSacra** [comment]
No problem, I just tested and it works perfectly again.
Thank you for your attention and celerity, and for the app itself of course.
